name: Terraform Validation and Apply

on:
  workflow_dispatch:
    inputs:
      terraform_block:
        description: 'Terraform block to execute in one line'
        required: true
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0 # Use a specific version as necessário

      - name: Initialize Terraform
        run: terraform init

      - name: Format Terraform block and write to file
        run: |
          # Replace occurrences of } and { with newlines and proper indentation
          echo "${{ github.event.inputs.terraform_block }}" | sed 's/{/ {\n  /g' | sed 's/}/\n}/g' > main.tf
          
          # Display the formatted file for debugging purposes
          cat main.tf
        shell: bash

      - name: Validate Terraform
        run: terraform validate

      - name: Apply Terraform
        if: ${{ success() }}
        run: terraform apply -auto-approve

      - name: Clean up Terraform block file
        run: rm -f main.tf
