name: Terraform Validator

on:
  push:
    branches:
      - main # Você pode ajustar isso para outra branch, se necessário
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.6

      - name: Initialize Terraform in the root directory
        working-directory: ${{ github.workspace }}
        run: terraform init

      - name: Validate Terraform in the root directory
        working-directory: ${{ github.workspace }}
        run: terraform validate

      - name: Apply Terraform in the root directory
        working-directory: ${{ github.workspace }}
        if: ${{ success() }}
        run: terraform apply -auto-approve
