name: Terraform Validation and Apply

on:
  workflow_dispatch:
    inputs:
      terraform_block:
        description: 'Terraform block to execute'
        required: true
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0 # Use a specific version as needed

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform
        run: |
          echo '${{ github.event.inputs.terraform_block }}' > main.tf
          terraform validate

      - name: Apply Terraform
        if: ${{ success() }}
        run: terraform apply -auto-approve

      - name: Clean up Terraform block file
        run: rm -f main.tf
